# API KEY
apiVersion: passport/v1
kind: ApiKey
metadata:
  name: spica-to-asset-apikey
spec:
  name: Secret Api Key For Asset Of Spica To Asset
  policies:
    - FunctionFullAccess
    - BucketReadOnlyAccess
---
# SPICA TO ASSET
apiVersion: dashboard/v1
kind: Dashboard
metadata:
  name: spica-to-asset
spec:
  name: Spica To Asset
  icon: settings_ethernet
  components:
    - name: convert
      url: api:/fn-execute/spicaToAssetDahsboard
      type: card
---
# FUNCTION - Convert Asset
apiVersion: function/v1
kind: Function
metadata:
  name: convert-asset
spec:
  description: Convert your spica to an asset
  language: javascript
  timeout: 200
  title: Spica To Asset
  code: ./function/spicatoasset.js
  runtime:
    name: Node
    language: Javascript
  environment:
    - name: API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: spica-to-asset-apikey
    - name: _IGNORE_
      value: "Dont't remove this environment !"
  dependency:
    - name: "@spica-devkit/bucket"
      version: ^0.9.11
    - name: "@spica-devkit/database"
      version: ^0.9.11
    - name: node-fetch
      version: ^3.0.0
    - name: yaml
      version: ^1.10.2
---
# TRIGGER - convertAsset
apiVersion: function/v1
kind: Trigger
metadata:
  name: convertAsset
spec:
  type: http
  name: convertAsset
  func: convert-asset
  active: true
  httpOptions:
    method: Post
    path: /convertAsset
---
# TRIGGER - spicaToAssetDahsboard
apiVersion: function/v1
kind: Trigger
metadata:
  name: spicaToAssetDahsboard
spec:
  type: http
  name: spicaToAssetDahsboard
  func: convert-asset
  active: true
  httpOptions:
    method: Get
    path: /spicaToAssetDahsboard